# version: 2
# updates:
#   - package-ecosystem: "gradle"
#     directory: "/server"
#     schedule:
#       interval: weekly
#       day: "sunday"
#   - package-ecosystem: "npm"
#     directory: "/client"
#     schedule:
#       interval: weekly
#       day: "sunday"
