INSERT INTO role(name) VALUES('ROLE_ADMIN');
INSERT INTO role(name) VALUES('ROLE_LECTURER');
INSERT INTO role(name) VALUES('ROLE_STAFF');
INSERT INTO role(name) VALUES('ROLE_STUDENT');


-- INSERT INTO student VALUES(2, 304357);
-- INSERT INTO lecturer VALUES(4, 'dr', 1);
-- INSERT INTO clerk VALUES(3, 1);
