INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_LECTURER');
INSERT INTO roles(name) VALUES('ROLE_STUFF');
INSERT INTO roles(name) VALUES('ROLE_STUDENT');

INSERT INTO faculties VALUES(1, 'WGGIOŚ');


INSERT INTO students VALUES(2, 304357);
INSERT INTO professors VALUES(4, 'dr', 1);
INSERT INTO clerks VALUES(3, 1);
